customhost = "employee.cdlp4u0kosbj.us-east-1.rds.amazonaws.com"
customuser = "aws_user"
custompass = "Bait3273"
customdb = "employee"
custombucket = "angkuanliang-employee"
customregion = "us-east-1"
